{% set name = "uv-dynamic-versioning" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 8642db686ce5c50417035e7a257ac73b7e5c3a7a32c33e45bd7e36ba22eeb648

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - dunamai >=1.26.1,<1.27.dev0
    - hatchling >=1.28,<2.dev0
    - jinja2 >=3.0,<4.dev0
    - tomlkit >=0.13,<1.dev0

test:
  imports:
    - uv_dynamic_versioning
  source_files:
    - tests
    # pyproject.toml is explicitly used in the tests
    - pyproject.toml
  requires:
    - pip
    - git
    - pytest >=8.4.2,<8.5.0
    - gitpython >=3.1.45,<3.2.0
  commands:
    - pip check
    # The tests want a git repo to work in and assume they are in
    # $SRC_DIR -- we aren't so create one
    - git init .
    - git config user.email you@example.com
    - git config user.name "Your Name"
    - git add .
    - git commit -m "dummy commit"
    - pytest tests

about:
  home: https://github.com/ninoseki/uv-dynamic-versioning
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Dynamic versioning based on VCS tags for uv/hatch project
  description: |
    poetry-dynamic-versioning influenced dynamic versioning tool for uv/hatch, powered by dunamai.
  doc_url: https://github.com/ninoseki/uv-dynamic-versioning
  dev_url: https://github.com/ninoseki/uv-dynamic-versioning

extra:
  recipe-maintainers:
    - ninoseki
    - tobiasraabe
