{% set name = "uv-dynamic-versioning" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: e853e0c5b2425a68005580325d4975a8c37b66015589ca45ef96e660fe0f8f16
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - dunamai >=1.25,<2
    - hatchling >=1.26,<2
    - jinja2 >=3.0,<4
    - tomlkit >=0.13,<1

# Skip tests that require git repository (not present in PYPI package)
{% set skip_git_tests = [
    "test_get_version_with_bump",
    "test_get_version_with_semver_tag",
    "test_get_version_with_prerelease_tag",
    "test_get_version_with_dev_tag",
    "test_get_version_with_bypass",
    "test_get_version_with_bypass_with_format",
    "test_get_version_with_invalid_combination_of_format_jinja_and_style",
    "test_without_dynamic_dependencies",
    "test_without_dependencies_in_config",
    "test_render_dependencies_with_semver",
    "test_render_dependencies_with_dirty",
    "test_render_dependencies_with_prerelease_tag",
    "test_render_dependencies_with_bypass_with_semver_tag",
    "test_render_dependencies_with_bypass_and_prerelease_tag",
    "test_render_dependencies_with_bypass_and_dev_tag",
    "test_with_semver_tag",
    "test_with_prerelease_tag",
    "test_with_dev_tag",
    "test_with_semver",
    "test_with_format",
    "test_with_bump",
    "test_with_dirty",
    "test_with_jinja2_format",
    "test_with_pattern",
    "test_from_file"
] %}

test:
  imports:
    - uv_dynamic_versioning
  source_files:
    - tests/
  requires:
    - pip
    - pytest >=8.4.2,<8.5.0
    - gitpython >=3.1.45,<3.2.0
  commands:
    - pip check
    - pytest tests/ -k "not ({{ skip_git_tests|join(' or ') }})"

about:
  home: https://github.com/ninoseki/uv-dynamic-versioning
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Dynamic versioning based on VCS tags for uv/hatch project
  description: |
    poetry-dynamic-versioning influenced dynamic versioning tool for uv/hatch, powered by dunamai.
  doc_url: https://github.com/ninoseki/uv-dynamic-versioning
  dev_url: https://github.com/ninoseki/uv-dynamic-versioning

extra:
  recipe-maintainers:
    - ninoseki
    - tobiasraabe
